from fastapi import APIRouter, Depends, HTTPException, UploadFile, File
from sqlalchemy.orm import Session
from typing import List, Optional
import httpx
import base64
import json
from database import get_db
from models.study_card import StudyCardSet
from schemas.study_card import StudyCardSetResponse
from core.dependencies import get_current_user
from core.config import settings
from models.user import User

router = APIRouter()

@router.post("/generate", response_model=StudyCardSetResponse, status_code=201)
async def generate_study_cards(
    subject: str,
    topic: str,
    student_id: int,
    file: Optional[UploadFile] = File(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Student uploads a NaCCA textbook page (PDF) or provides a topic.
    Claude AI generates bite-sized study flashcards from the content.
    """
    if not settings.ANTHROPIC_API_KEY:
        raise HTTPException(
            status_code=400,
            detail="Anthropic API key not configured"
        )

    messages_content = []

    if file and file.content_type == "application/pdf":
        pdf_bytes = await file.read()
        pdf_base64 = base64.b64encode(pdf_bytes).decode("utf-8")
        messages_content.append({
            "type": "document",
            "source": {
                "type": "base64",
                "media_type": "application/pdf",
                "data": pdf_base64
            }
        })

    prompt = f"""
You are a study assistant helping a Ghanaian JHS/SHS student revise
using NaCCA-aligned content.

Generate 8 study flashcards for:
Subject: {subject}
Topic: {topic}

{"Use the uploaded NaCCA textbook page as your source." if file else "Use your knowledge of the Ghana NaCCA curriculum."}

Each card should have a clear question on one side and a concise,
accurate answer on the other.

Respond ONLY with a valid JSON array. No preamble or explanation.
Format exactly like this:
[
  {{
    "question": "What is ...?",
    "answer": "... is ..."
  }},
  {{
    "question": "State the law of ...",
    "answer": "The law states that ..."
  }}
]
"""
    messages_content.append({"type": "text", "text": prompt})

    try:
        response = httpx.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": settings.ANTHROPIC_API_KEY,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={
                "model": "claude-sonnet-4-6",
                "max_tokens": 1500,
                "messages": [{"role": "user", "content": messages_content}]
            },
            timeout=30.0
        )
        data = response.json()
        text = data["content"][0]["text"].strip()
        text = text.replace("```json", "").replace("```", "").strip()
        cards = json.loads(text)

        card_set = StudyCardSet(
            title=f"{subject} — {topic}",
            subject=subject,
            topic=topic,
            student_id=student_id,
            cards=cards,
            source_file=file.filename if file else None
        )
        db.add(card_set)
        db.commit()
        db.refresh(card_set)
        return card_set

    except json.JSONDecodeError:
        raise HTTPException(
            status_code=500,
            detail="AI returned invalid format. Please try again."
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/student/{student_id}", response_model=List[StudyCardSetResponse])
def get_student_study_cards(
    student_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Get all study card sets generated by a student."""
    return db.query(StudyCardSet).filter(
        StudyCardSet.student_id == student_id
    ).all()

@router.get("/{set_id}", response_model=StudyCardSetResponse)
def get_study_card_set(
    set_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Get a specific study card set."""
    card_set = db.query(StudyCardSet).filter(
        StudyCardSet.id == set_id
    ).first()
    if not card_set:
        raise HTTPException(status_code=404, detail="Study card set not found")
    return card_set

@router.delete("/{set_id}", status_code=204)
def delete_study_card_set(
    set_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Delete a study card set."""
    card_set = db.query(StudyCardSet).filter(
        StudyCardSet.id == set_id
    ).first()
    if not card_set:
        raise HTTPException(status_code=404, detail="Study card set not found")
    db.delete(card_set)
    db.commit()