import React, { useEffect, useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import PageHeader from '../components/PageHeader';
import LoadingState, { EmptyState, ErrorState } from '../components/LoadingState';
import { fetchMyAttendance, fetchMyScores } from '../services/portalService';
import { calcAttendanceRate, calcAverageScore, groupScoresBySubject, scoreColor } from '../utils/format';

const monthLabel = (date) => new Date(date).toLocaleDateString('en-GB', { month: 'short', year: '2-digit' });
export default function Performance() {
  const [scores, setScores] = useState([]); const [attendance, setAttendance] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(null);
  useEffect(() => { Promise.all([fetchMyScores(), fetchMyAttendance()]).then(([scoreRes, attendanceRes]) => { setScores(scoreRes.data); setAttendance(attendanceRes.data); }).catch((err) => setError(err.response?.data?.detail || 'Failed to load performance.')).finally(() => setLoading(false)); }, []);
  const subjectBreakdown = useMemo(() => groupScoresBySubject(scores), [scores]);
  const scoreTrend = useMemo(() => scores.slice().sort((a,b) => new Date(a.recorded_at) - new Date(b.recorded_at)).map((item) => ({ month: monthLabel(item.recorded_at), score: item.score })), [scores]);
  const attendanceTrend = useMemo(() => { const groups = {}; attendance.forEach((item) => { const key = monthLabel(item.date); if (!groups[key]) groups[key] = []; groups[key].push(item); }); return Object.entries(groups).map(([month, records]) => ({ month, attendance: calcAttendanceRate(records) })); }, [attendance]);
  if (loading) return <LoadingState />; if (error) return <ErrorState message={error} />;
  const average = calcAverageScore(scores); const attendanceRate = calcAttendanceRate(attendance);
  return <div><PageHeader title="My performance" subtitle="Track how you're growing across subjects and terms." />{scores.length === 0 && attendance.length === 0 ? <EmptyState message="Your performance will appear here once your teacher records scores or attendance." /> : <><div className="grid grid-cols-2 md:grid-cols-3 gap-4 mb-6">{[{ label: 'Weighted avg', value: `${average}%` }, { label: 'Attendance', value: `${attendanceRate}%` }, { label: 'Subjects assessed', value: subjectBreakdown.length }].map((stat) => <div key={stat.label} className="edu-card p-4"><p className="text-2xl font-bold text-slate-900">{stat.value}</p><p className="text-xs text-slate-500 mt-0.5">{stat.label}</p></div>)}</div><div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">{scoreTrend.length > 0 && <div className="edu-card p-5"><h3 className="font-semibold text-slate-900 text-sm mb-4">Score trend</h3><ResponsiveContainer width="100%" height={220}><LineChart data={scoreTrend}><CartesianGrid strokeDasharray="3 3" stroke="#E2E8F0" /><XAxis dataKey="month" tick={{ fontSize: 12, fill: '#94A3B8' }} /><YAxis domain={[0, 100]} /><Tooltip /><Line type="monotone" dataKey="score" stroke="#0A192F" strokeWidth={2} /></LineChart></ResponsiveContainer></div>}{attendanceTrend.length > 0 && <div className="edu-card p-5"><h3 className="font-semibold text-slate-900 text-sm mb-4">Attendance %</h3><ResponsiveContainer width="100%" height={220}><BarChart data={attendanceTrend}><CartesianGrid strokeDasharray="3 3" stroke="#E2E8F0" vertical={false} /><XAxis dataKey="month" tick={{ fontSize: 12, fill: '#94A3B8' }} /><YAxis domain={[0, 100]} /><Tooltip /><Bar dataKey="attendance" fill="#22C55E" radius={[4,4,0,0]} /></BarChart></ResponsiveContainer></div>}</div>{subjectBreakdown.length > 0 && <div className="edu-card p-5"><h3 className="font-semibold text-slate-900 text-sm mb-4">Subject breakdown</h3><div className="space-y-3">{subjectBreakdown.map((item) => <div key={item.subject} className="flex items-center gap-4"><span className="text-sm text-slate-600 w-20 shrink-0">{item.subject}</span><div className="flex-1 h-6 bg-slate-100 rounded-full overflow-hidden"><div className="h-full rounded-full" style={{ width: `${item.score}%`, backgroundColor: scoreColor(item.score) }} /></div><span className="text-sm font-medium text-slate-700 w-8 text-right">{item.score}</span></div>)}</div></div>}</>}</div>;
}
